### ISSUE TITLE
Remove gluon and photon parameter requirements from atlas detector

### ISSUE THREAD

**Issue by knutzk** [KLFitter/KLFitter#36]
## Description

The classes for the atlas detector require parameter sets for gluons and photons, and also provide functionality for them. As none of those particle types is used in any of the likelihoods, those requirements could be removed. If parameter sets don't include those parameterisations, this causes warnings for missing files.

## Expected Behavior

Only require the files that are actually necessary for full functionality.

## Actual Behavior

Required files include those for photons and gluons, which are not used anywhere.

## Context

Users are confused by warnings issued by the detector classes, when parameter sets do not contain parameterisations for gluons and photons.

## Your Environment

* KLFitter version used: 1.0.0
* BAT version used: 0.9.4.1
* ROOT version used: 6.10/04
* Operating System and version: SL6
* Link to your project:

**Comment by knutzk** [comment]
Hi Olaf, thanks for the feedback! I guess we have different opinions here then ... If we only remove the TF requirements for gluons and photons from the detector class, I think we should think about a different strategy for what gets checked when and is required where. We basically have three different levels:
1. what's supported by the detector class,
2. what's provided by the TF parameter set,
3. what's needed by the likelihood class to function.

At the moment, the (1) and (2) are _required_ to be identical, which is maybe not the way to go. In the end, I think (3) should be the baseline, while (1) and (2) can always provide _more_ than necessary, and don't have to match each other. So I would suggest to:
- not issue warnings by the detectors, if not all of their supported resolution functions have parameters,
- and instead have the likelihoods do the check whether the detector supports everything they need, and whether the TF set provides parameters for that.

Those will require quite a lot of changes, but in the end would be a much more consistent setup, that avoids unnecessary warnings, but issues errors if something is missing. What do you think?

**Comment by nackenho** [comment]
I agree, that would be the best way to go. I think in general the detector classes should be as general as possible, if the TF parameter are not provided currently, that should have an impact on the Detector class. I would also like to avoid having detector classes for all possible setups of TFs - I think that makes no sense. We could write dummy files which would then initiate a warning in the likelihood if it is trying to use the TFs

**Comment by knutzk** [comment]
I'm closing this to centralise the discussion in #56.
