### ISSUE TITLE
Wrong Energy Resolution Formula in ResGaussE

### ISSUE THREAD

**Issue by tkallage** [KLFitter/KLFitter#48]
The formula for the energy resolution, which was extracted from the Delphes detector card for the Snowmass detector, has a wrong implementation in KLFitter.

## Description

The formula in the Snowmass detector card is of the following form:
```
sigma = sqrt(a^2 * E^2 + b^2 * E + c^2)
```
but it is implemented with the same parameters in the following form:
```
sigma = a * E + b * sqrt(E) + c
```
The difference is not negligible (example for jet resolution for |eta| in [0, 1.7])
![Comparison](https://image.ibb.co/gtv9AT/compare_sigma.png)

Affected file:
https://github.com/KLFitter/KLFitter/blob/master/src/ResGaussE.cxx
Only used by:
https://github.com/KLFitter/KLFitter/blob/master/src/DetectorSnowmass.cxx
(in this repository, could be used in other projects using KLFitter)

## Expected Behavior

The formula should be
```
sigma = sqrt(a^2 * E^2 + b^2 * E + c^2)
```
as in the delphes detector card from HepSim for the Snowmass detector:
http://atlaswww.hep.anl.gov/hepsim/soft/detectors/delphes_dpf1/card.tcl
resolution formula on lines 289-292

## Actual Behavior

Implemented in KLFitter/ResGaussE:
```
sigma = a * E + b * sqrt(E) + c
```
https://github.com/KLFitter/KLFitter/blob/373a4fea57fe3ca9e2cb434c77d77ac0ed49cf9b/src/ResGaussE.cxx#L42-L44

## Possible Fix

Suggested fix: Change formula implemented in KLFitter/ResGaussE  #47 

Alternative: Fit parameters of implemented function to original function. This would have to be done for jets and electrons in 3 eta bins each.
Works in principle (fitted function in orange):
![Fitted Comparison](https://image.ibb.co/h1Wuc8/sigma_sigma_new.png)

## Steps to Reproduce

Reproducible with example-top-ljets.cxx or test-ljets-lh.cxx

## Your Environment

* KLFitter version used: 1.1.0

**Comment by knutzk** [comment]
Hi @tkallage,

Thanks for the detailed explanation! Do I understand you correctly, that this not only affects the parameterisation of the jets/HCal, but also the electron parameters?

Cheers, Knut

**Comment by tkallage** [comment]
Hi @knutzk,

Yes correct, I also only noticed this while doing the edit of the PR.
You can see this in the implementation of the DetectorSnowmass class:
https://github.com/KLFitter/KLFitter/blob/373a4fea57fe3ca9e2cb434c77d77ac0ed49cf9b/src/DetectorSnowmass.cxx#L34-L44
and the electron transfer functions, where the detector card is cited:
https://github.com/KLFitter/KLFitter/blob/373a4fea57fe3ca9e2cb434c77d77ac0ed49cf9b/data/transferfunctions/snowmass/par_energy_electrons_eta1.txt#L1-L8

**Comment by knutzk** [comment]
HI @tkallage,

Ok, good to know! So, both jet and electron parameterisations get fixed with this change? If yes, I think this can be merged.

Cheers, Knut

**Comment by tkallage** [comment]
Hi @knutzk 

Correct, as both resolutions are implemented with the `ResGaussE` class, this fixes both jet and electron resolutions.

**Comment by knutzk** [comment]
Ok, I'm merging this now. Thanks again!
