### ISSUE TITLE
Make KLFitter::Particles::AddParticle interface (and others) const-correct

### ISSUE THREAD

**Issue by TJKhoo** [KLFitter/KLFitter#49]
## Description

At present, `KLFitter::Particles::AddParticle` requires the user to pass in a non-const `TLorentzVector&`. This means that if one already has a const `TLorentzVector`, e.g. from an experiment's EDM, this has to be copied into another `TLorentzVector` or worse `const_cast`-ed. Neither of these is elegant, and the former incurs overhead from the copy operation. Furthermore, this leaves open the possibility of accidentally changing the input particles.

If the KLFitter operations do not modify the particles, then the input `TLorentzVector` parameter ought to be const. This is an interface change, but requires no changes to client code, but would allow cleaner handling.

## Fix

Enforce const-correctness in `KLFitter::Particles::AddParticle`, and in other setter methods (e.g. `KLFitter::LikelihoodBase` constructor, `SetDetector`, `SetParticlesPermuted`, ...)

**Comment by knutzk** [comment]
Hi @TJKhoo, thanks! Is this what you thought of? If yes, I will create a PR.
https://github.com/KLFitter/KLFitter/compare/0b187a9cb89a03600436b987b6279f0ae3ad4d06...knutzk:const-correctness
Ideally, I would even like to switch to `const TLorentzVector& vec`, but that would possibly break interfaces outside of KLFitter. I would keep that on a list of things to do for an interface-breaking version update.

**Comment by TJKhoo** [comment]
Hi @knutzk,

Yes, exactly. I am myself not so scrupulous about using 2x const, but there is no good reason not to ;)

As noted, there are some other instances you could deal with in other classes, but I think this is probably the most important change in practical terms because these TLorentzVectors could really come from external sources.

If you really wished to gradually encourage users, you could already change the base implementation to use the `const TLorentzVector& vec` style, and just have the `const TLorentzVector* const` overload forward to that and print a deprecation message.

**Comment by knutzk** [comment]
Hi @TJKhoo, good point! I will add the function overloading, and keep the pointer version for compatibility reasons, until we bump up our major release number.

**Comment by johanneserdmann** [comment]
Hi @knutzk,
I'd prefer a solution that does not break codes outside of KLFitter.

**Comment by knutzk** [comment]
@johanneserdmann, well, it won't. If we do what TJ suggested, we will remain compatible with everyone, until we decide to remove the pointer implementation (which would be something for a major release, like 2.0).

**Comment by johanneserdmann** [comment]
Hi @knutzk,
this is exactly what I meant. I proposed to go in the way that TJ originally suggested.

**Comment by knutzk** [comment]
Hi @johanneserdmann, ok, thanks, then it was maybe a misunderstanding. That's what I was suggesting as well.

**Comment by knutzk** [comment]
Hi all, I created PR #51 addressing this issue. As discussed, I added const ref implementations of the `AddParticle()` functions, and the pointer versions of those functions internally call the const ref implementations. This shouldn't break any interface to KLFitter, until we remove those overloaded pointer implementations in the next major release.
