### ISSUE TITLE
Make angular likelihoods derived classes of l+jets likelihood

### ISSUE THREAD

**Issue by knutzk** [KLFitter/KLFitter#50]
## Description

The angular likelihoods `LikelihoodTopLeptonJets_Angular` and `LikelihoodTopLeptonJets_JetAngles` are essentially modifications of the standard `LikelihoodTopLeptonJets`, thus, they share a lot of the implementation code. However, all of them are currently derived independently from `LikelihoodBase`, that is, a lot of the same code is implemented in three different classes. To reduce the code clutter, the two angular likelihoods should derive from the l+jets likelihood and only reimplement, what is actually changed.

## Expected Behavior

Modifications of the l+jets likelihood should be derived from it and only reimplement functions that need actual changes.

## Actual Behavior

All three classes have the same base class, but are implemented independently. As a consequence, 80%+ of the classes' implementations are identical.

## Your Environment

* KLFitter version used: latest (v1.1.0)

**Comment by knutzk** [comment]
/cc @KLFitter/core, to make you aware of this issue. I think we should fix this, because it would drastically reduce the size of those classes and help to understand, what they actually do differently compared to the l+jets likelihood. What do you think?

P.S. I created a "team" in the KLFitter group called _core_ and added you all to it. You can notify this team with `@KLFitter/core`. If you want to stay updated with everything happening in this repository, you should also use the "watch" option (next to forking and starring).

**Comment by nackenho** [comment]
That would probably make sense and I don't have objections, but given that the angular classes have never really been used in analysis (afaik), I think this is not high priority. Thanks for creating the core group.

**Comment by knutzk** [comment]
I agree, it's not any important. But I basically have the necessary changes ready, since I went through those classes a couple of weeks ago and did some cleanup. So if that's fine with you, I will create a PR.

**Comment by johanneserdmann** [comment]
That change is fine with me. Both likelihoods are very similar to the lepton+jets one.
