### ISSUE TITLE
Adjust requirements for transfer function parameterisations

### ISSUE THREAD

**Issue by knutzk** [KLFitter/KLFitter#56]
## Description

I'll use this issue to summarise a set of problems that arises with the current handling of transfer function parameters and detector implementations within the KLFitter package. Some of these are already mentioned in #36 and #37, but for a better discussion, we should continue with this ticket.

We essentially have three levels of dependencies:
1. Parameters provided by the TF parameter set. Naturally, only if parameterisations for a specific object type are available in the TF parameter set, it can be used in a likelihood fit.
2. What's supported by the detector class. Only if the detector has an existing parameterisation for an object type, it can be used in a likelihood, i.e. the detector class needs to explicitly pick up the parameters from the TF parameter set, and know how to handle them.
3. What's needed by the likelihood class to function.

At the moment, (1) and (2) are required to be identical, which is maybe not the way to go. In the end, I think (3) should be the baseline, while (1) and (2) can always provide more than necessary (not less, of course), and also (1) and (2) don't have to match each other. So I would suggest to:

not issue warnings by the detectors, if not all of their supported resolution functions have parameters,
and instead have the likelihoods do the check whether the detector supports everything they need, and whether the TF set provides parameters for that.
Those will require quite a lot of changes, but in the end would be a much more consistent setup, that avoids unnecessary warnings, but issues errors if something is missing. What do you think?

## Expected Behavior

The expected behaviour would be that the likelihood defines the baseline: any object type/parameterisation that is used in the likelihood calculation, must be provided for the likelihood to function. For example, if the likelihood includes photons, we must have a detector implementation with a parameterisation of photon transfer functions, and the TF parameter set must include the appropriate parameters for them. Of course the detector implementation may provide more than what is needed for the likelihood, and the TF parameter set may contain more parameters than the needed ones.
Long story short: the code should fail (and should _only_ fail) if the likelihood requires something that is either not implemented in the detector class, or does not have parameters in the TF parameter set. If TF parameter set and detector implementation don't match, e.g. the detector supports photons, but the TF parameter does not include photons, no warnings/errors should be raised, unless the likelihood needs that information. 

## Actual Behavior

At the moment, (1) and (2) are required to be identical, i.e. the detector class raises warnings when not all parameters are provided by the TF parameter set. Also, if the detector class does not overwrite the base class implementation of a resolution function, e.g. of photons, no error/warning is raised. 

## Possible Fix

We need to add explicit checks in the detector classes, if certain methods are (dummy) base class implementations or if they were reimplemented in a derived class. We also need checks for the TF parameters, but only if the corresponding resolution functions are actually being called, not when the detector class is initialised. 

## Context

Users are confused by warnings issued by the detector classes, when parameter sets do not contain parameterisations for certain particle types. Those combinations should be possible without raising warning/errors, as long as the likelihood doesn't need that information.

## Your Environment

* KLFitter version used: v1.1.0
* BAT version used: 0.9.4.1
* ROOT version used: 6.10/04

**Comment by knutzk** [comment]
@KLFitter/core. Although we have collected a few changes since v1.1.0, I think it would be nice to have this implemented before releasing v1.2.0. What do you think? I myself, unfortunately, won't have much time to work on it in the next weeks ...

**Comment by nackenho** [comment]
Well, I don't think this change is a high priority right now and I don't think we need to release a new tag, since the last changes didn't have a real impact for the user or not?

**Comment by knutzk** [comment]
Agreed, the recent changes won't motivate a new release. But I think the above issue _is_ something we have to work on ~soonish, since it prevents ATLAS to switch to the 13 TeV transfer function parameterisation by default (see discussion in [ATLAS top reco meeting](https://indico.cern.ch/event/746909/) yesterday and [this JIRA ticket](https://its.cern.ch/jira/browse/ANALYSISTO-624)).

**Comment by johanneserdmann** [comment]
I agree with Knut that this is a useful change to make, but as pointed out here in the ticket, this will require significant work from our side. I also agree with Olaf that we can make a tag now and a tag later - we don't need to wait.

**Comment by nackenho** [comment]
@knutzk : I don't understand why this prevents TopReco to switch to 13 TeV TFs, I mean, yes, warning messages are annoying, but most user won't see them and if it has an important impact I would suggest them to switch and not to wait until all the changes are done on our side...

**Comment by knutzk** [comment]
@johanneserdmann, I agree, we don't depend on the above change for a new release. But nothing collected after v1.1.0 so far really motivates a new release either, so I would wait until we have something that improves the overall user performance and/or fixes problems with the code.

**Comment by knutzk** [comment]
@nackenho, nobody prevents users to switch to the new transfer functions – they are available within the ATLAS framework, and it's just about switching an option in the configuration file. But I don't like the idea of making something a default when our code starts spitting our warnings that most people won't understand.

**Comment by knutzk** [comment]
@johanneserdmann, sure that would be possible. We could just comment the initialisation in the `DetectorAtlas_8TeV` constructor, e.g.:
```c++
  fResEnergyLightJet_eta1 = std::unique_ptr<ResolutionBase>(new KLFitter::ResDoubleGaussE_4{Form("%s/par_energy_lJets_eta1.txt", folder.c_str())});
  fResEnergyBJet_eta1     = std::unique_ptr<ResolutionBase>(new KLFitter::ResDoubleGaussE_4{Form("%s/par_energy_bJets_eta1.txt", folder.c_str())});
  // fResEnergyGluonJet_eta1 = std::unique_ptr<ResolutionBase>(new KLFitter::ResDoubleGaussE_1{Form("%s/par_energy_gluon_eta1.txt", folder.c_str())});
  fResEnergyElectron_eta1 = std::unique_ptr<ResolutionBase>(new KLFitter::ResDoubleGaussE_5{Form("%s/par_energy_Electrons_eta1.txt", folder.c_str())});
  fResEnergyMuon_eta1     = std::unique_ptr<ResolutionBase>(new KLFitter::ResDoubleGaussPt{Form("%s/par_energy_Muons_eta1.txt", folder.c_str())});
  // fResEnergyPhoton_eta1   = std::unique_ptr<ResolutionBase>(new KLFitter::ResGauss{Form("%s/par_energy_photon_eta1.txt", folder.c_str())});
```
and comment the safety checks in `DetectorBase::Status()` for gluons and photons. We would have to make sure, though, that no one is using the eta and phi parameterisations for jets, because those also produce warnings.

**Comment by johanneserdmann** [comment]
That sounds good to me. Concerning the eta and phi parameterizations, I don't think anybody is using them at the moment, actually.
