### ISSUE TITLE
Treatment of TFs when the provided path is wrong

### ISSUE THREAD

**Issue by TomasDado** [KLFitter/KLFitter#58]
## Description
KLFitter doesn't stop when the provided TF are invalid. There should be a protection that stops the code when TF are invalid and are needed by the given likelihood.

## Expected Behavior
KLFitter should print an error and stop immediately.

## Actual Behavior
KLFItter prints warnings that TFs do not exist but continues running and burning CPUs.

## Context
This can results in useless runs on the grid that produce non-sense results.

## Your Environment
* KLFitter version used: 1.0.0

**Comment by johanneserdmann** [comment]
I agree that this would be a useful thing to change.

**Comment by knutzk** [comment]
@TomasDado, as far as I see it, these changes should be addressed in the proposed changes of PR #61? Or do you think we should add something else?

**Comment by TomasDado** [comment]
@knutzk I think #61 fixes all problems mentioned in this issue. 
Thanks for the changes!
